CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE "WarrantyStatus" AS ENUM ('WARRANTY_NONE', 'WARRANTY_ACTIVE', 'WARRANTY_USED', 'WARRANTY_EXPIRED');

ALTER TABLE "ServiceOrder"
ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP,
ADD COLUMN IF NOT EXISTS "guaranteeUsed" BOOLEAN NOT NULL DEFAULT false;
